export const Data = [
    {
        id: 1,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },
    {
        id: 2,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },
    {
        id: 3,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },
    {
        id: 4,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },

    {
        id: 5,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },

    {
        id: 6,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },
    {
        id: 7,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },
    {
        id: 8,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },
    {
        id: 9,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },
    {
        id: 10,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },
    {
        id: 11,
        title: "Mèo nằm",
        author: "meo",
        src: "/assets/images/anh1.jpg",
        type: "Miễn phí",
    },
]