export const TransactionData = [
    {
        id: 1,
        code: 'athajskịd',
        title: "Điều bí mật",
        author: "Hân Như",
        src: "/assets/images/anh1.jpg",
        money: "57,000",
        time: "22h 22/01/2024",
        state: "Thành công",
        payments: "VN Pay",
        account: "hahaha",
    },
    {
        id: 2,
        code: 'athajskịd',
        title: "Điều bí mật",
        author: "Hân Như",
        src: "/assets/images/anh1.jpg",
        money: "57,000",
        time: "22h 22/01/2024",
        state: "Thành công",
        payments: "VN Pay",
        account: "hahaha",
    },
    {
        id: 3,
        code: 'athajskịd',
        title: "Điều bí mật",
        author: "Hân Như",
        src: "/assets/images/anh1.jpg",
        money: "57,000",
        time: "22h 22/01/2024",
        state: "Thành công",
        payments: "VN Pay",
        account: "hahaha",
    },
    {
        id: 4,
        code: 'athajskịd',
        title: "Điều bí mật",
        author: "Hân Như",
        src: "/assets/images/anh1.jpg",
        money: "57,000",
        time: "22h 22/01/2024",
        state: "Thành công",
        payments: "VN Pay",
        account: "hahaha",
    }
]